@startuml
skinparam packageStyle rectancle
left to right direction

actor Administrator

package Server {

  Database Database

  package Backend {
  }
}

package Frontend {
  package Backoffice {
    ' Main
    (Manage users) as mu
    (Manage posts) as mp
    (Manage comments) as mc
    (Analytics)

    ' User
    (Create a user)
    (Delete a user)
    (Edit a user)
    (Reset user password)
    ' --
    (Select a user)
    (Fill informations)
    (Send an email)

    ' Posts
    package manage_blog_posts {
      (Create a blog post)
      (Edit a blog post)
      (Delete a blog post)
    }

    ' Comments
    (Edit a comment)
    (Delete a comment)
    (List reported comments)
  }
}

Administrator -- mu
Administrator -- mp
Administrator -- mc
Administrator -- Analytics

' User
mu -- (Reset user password)
mu -- (Edit a user)
mu -- (Create a user)
mu -- (Delete a user)
' --
(Reset user password) ..> (Send an email) : include
(Reset user password) ..> (Select a user) : include
(Edit a user) ..> (Select a user) : include
(Delete a user) ..> (Select a user) : include
(Edit a user) ..> (Fill informations) : include
(Create a user) ..> (Fill informations) : include
(Edit a user) ..> (Send an email) : include
(Create a user) ..> (Send an email) : include

' Posts
mp -- manage_blog_posts

' Comments
mc -- (Edit a comment)
mc -- (Delete a comment)
mc -- (List reported comments)

' Infra
Frontend -- Backend
Backend -- Database

@enduml
