@startuml
left to right direction

title Blog use case

'  Actors
actor Admin
actor "Logged In User" as User
actor Visitor

' <<system>>
Database Database <<system>>

' Package definition
package Blog {
    usecase "Post listing" as PostListing
    usecase "Add a blog post" as AddBlogPost
    usecase "Delete a blog post" as DeleteBlogPost
    usecase "Update a blog post" as UpdateBlogPost
    usecase "Read a blog post" as ReadBlogPost
    usecase "Delete a comment" as DeleteComment
    usecase "Comment a blog post" as CommentBlogPost
    usecase "Contact form" as ContactForm
    usecase "Active or deactivate a comment" as toggleComment
}

' Relations
Admin -|> User
User -|> Visitor

Visitor -- ReadBlogPost
Visitor -- PostListing
Visitor -- ContactForm

User -- CommentBlogPost

Admin -- AddBlogPost
Admin -- DeleteBlogPost
Admin -- UpdateBlogPost
Admin -- toggleComment

Admin -- DeleteComment

Blog --- Database

@enduml
