@startuml
skinparam packageStyle rectancle
left to right direction

actor Administrator
actor Author
actor Member
actor Guest 


package Server {

  Database Database

  package Backend {
  }
}

package Frontend {
  package Frontoffice {
    (Homepage) as h
    (Blog listing) as bl

    usecase mbp as "Manage blog posts
    --
    EXT: If he's the owner 
    or an administrator"


    (Login / Register) as lr
    (Comment a blog post) as cbp
    (Contact form) as cf

    (Create a blog post)
    (Edit a blog post)
    (Delete a blog post)

    (Paginate posts)

    (Fill the form)
  }
}

Administrator -|> Author
Author -|> Member
Member -|> Guest

Guest -- h
Guest -- bl
Guest -- lr
Guest -- cf

Member -- cbp

Author -- mbp

mbp -- (Create a blog post)
mbp <.. (Edit a blog post) : <<extends>>
mbp <.. (Delete a blog post) : <<extends>>

(Create a blog post) -- Backend
(Edit a blog post) -- Backend
(Delete a blog post) -- Backend

Backend -- Database

lr ..> (Fill the form) : include
cf ..> (Fill the form) : include
cbp ..> (Fill the form) : include

bl -- (Paginate posts)

@enduml
