@startuml
left to right direction

title Manage users use case

' Actors
actor Admin

'  <<system>>
Database Database <<system>>
actor "Symfony Mailer" as SymfonyMailer <<system>>

' Package definition
package "Manage users" as ManageUsersPackage {
    usecase "User listing" as UserListing
    usecase "Activate or deactivate a user" as toggleUser
    usecase "Delete a user" as DeleteUser
    usecase "Set/unset admin" as toggleAdmin
}

' Relations
Admin -- UserListing
Admin -- toggleUser
Admin -- DeleteUser
Admin -- toggleAdmin

ManageUsersPackage -- Database

toggleUser -- SymfonyMailer

@enduml
