@startuml
skinparam packageStyle rectancle
left to right direction

actor Administrator
actor Author
actor Member
actor Guest 

package Frontend {
  package Frontoffice {
    (Homepage) as h
    (Blog listing) as bl
    (Manage blog posts) as mbp
    (Login / Register) as lr
    (Comment a blog post) as cbp
    (Contact form) as cf
    (Report a comment) as rc

    (Manage his account)
  }

  package Backoffice {
    (Manage users) as mu 
    (Manage posts) as mp
    (Manage comments) as mc
    (Analytics)
  }
}

package Server {

  Database Database

  package Backend {
    entity Controllers
    entity Models
    entity Views
  }
}

Administrator -|> Author
Author -|> Member
Member -|> Guest

Guest -- h
Guest -- bl
Guest -- lr
Guest -- cf

Member -- cbp
Member -- rc
Member -- (Manage his account)

Author -- mbp

Administrator -- mu
Administrator -- mp
Administrator -- mc
Administrator -- Analytics

Frontend <--> Server
Models -- Database
Controllers -- Models
Controllers -- Views

@enduml
