@startuml

title Add a blog post
autonumber

actor Client
entity Server
Database Database

activate Server

Client -> Server : Add a blog post request

Server --> Client : Display Add a blog post page

deactivate Server

activate Client

Client -> Server : Add a blog post request

deactivate Client

activate Server

Server -> Server : Verify data sent

alt A form value is invalid
    Server --> Client : Display errors messages
end

Server -> Database : Save new blog post

Server --> Client : Redirect to the new blog post

deactivate Server

@enduml
