@startuml

title Comment a blog post
autonumber

actor Client
entity Server
Database Database

activate Server

Client -> Server : Request single post page
Server --> Client : Display single post page

deactivate Server

activate Client

Client -> Server : Add a new comment request

deactivate Client

activate Server

Server -> Server : Validate data sent

alt A form value is invalid
    Server -> Client: Display errors messages
end


Server -> Database: Save comment

Server --> Client: Display single post page with the new post

deactivate Server

@enduml
