@startuml

title Delete a report
autonumber

actor Client 
entity Server 
Database Database 

Client -> Server : Delete report request

activate Server

Server -> Server : Check client has admin role

alt Client is not admin 
    Server --> Client : Redirect to "Login" page
end

Server -> Database : Delete report by id

Server --> Client : Success

deactivate Server

@enduml