@startuml

title Delete a comment
autonumber

actor Client 
entity Server 
Database Database 

Client -> Server : Delete comment request

activate Server

Server -> Server : Check client is owner or admin

alt Client is not the owner or an admin
    Server --> Client : Redirect to "Login" page
end

Server -> Database : Delete comment by id

Server --> Client : Success

deactivate Server

@enduml