@startuml

title Delete a blog post
autonumber

actor Client
entity Server
Database Database

Client -> Server : Delete blog post request

activate Server

Server -> Server : Check is admin

alt Client is not an admin
    Server --> Client : Redirect to "Login" page
end

Server -> Database : Delete blog post by id

Server --> Client : Success

deactivate Server

@enduml
