@startuml

title List reported comments
autonumber 

actor Client
entity Server
Database Database

Client -> Server : List reported comments request
note over Client
Including GET sorting and
pagination parameters
end note

activate Server

Server -> Server : Check client has admin role

alt Client is not admin 
    Server --> Client : Redirect to "Login" page
end

Server -> Database : Get reported comments

Server --> Client : Display reported comments

deactivate Server

@enduml