@startuml

title Report a comment 
autonumber

actor Client 
entity Server
Database Database 

activate Server

Client -> Server : Report a comment request 

Server -> Server : Check user is logged in

alt User is not logged in 
    Server --> Client : Redirect to "Login" page
end

Server -> Database : Check comment isn't already reported by the user

alt User already reported this comment 
    Server --> Client : Display message
end

Server -> Database : Save report 

Server --> Client : Success message 

deactivate Server

@enduml