@startuml

title Update a blog post
autonumber

actor Client
entity Server
Database Database

activate Server

Client -> Server : Update a blog post request

Server --> Client : Display form

deactivate Server

activate Client

Client -> Server : Update a blog post request

deactivate Client

activate Server

Server -> Server : Validate data sent

alt A form value is invalid
    Server --> Client : Display errors messages
end

Server -> Database : Update blog post

Server -> Client : Redirect to the blog post page

deactivate Server

@enduml
