@startuml

title Login
autonumber

actor Client
entity Server
Database Database

Client -> Server : Login page request

activate Server

alt Client is already logged in
    Server --> Client : Redirect to the homepage
end

Server --> Client : Display login form

deactivate Server

activate Client

Client -> Server : Login request

deactivate Client

activate Server

Server -> Database : Verify that the user exists

Server -> Database : Verify password

alt User doesn't exists or password is invalid
    Server --> Client : Display error message
end

Server -> Server : Create the user session

Server --> Client : Redirect to the homepage

deactivate Server

@enduml
