@startuml

title Register
autonumber

actor Client
entity Server
Database Database

Client -> Server : Register page request

activate Server

alt Client is already logged in
    Server --> Client : Redirect to the homepage
end

Server -> Client : Display register form

deactivate Server

activate Client

Client -> Server : Register request

deactivate Client

activate Server

Server -> Server : Verify data sent

alt A form value is invalid
    Server --> Client : Display errors messages
end

Server -> Database : Register the user

Server --> Client : Redirect to the homepage page

deactivate Server

@enduml
