@startuml

title Reset password
autonumber

actor Client
entity Server 
entity "Symfony Mailer" as SymfonyMailer
Database Database 

Client -> Server : Reset password page request

activate Server

alt Client is already logged in
    Server --> Client : Redirect to "My account" page
end

Server --> Client : Display email address input

deactivate Server

activate Client

Client -> Client : Fill email address
Client -> Client : Validate email input

alt Email format is not valid
    Client -> Client : Display error message
end

Client -> Server : Reset password request 

deactivate Client

activate Server

Server -> Database : Get email's associated user

Server -> Server : Verify user

alt User exists
    Server -> SymfonyMailer : Send a mail containg reset password url
end

Server --> Client : Success message

deactivate Server

Client -> Server : Authorized reset password request
note left
When the user has clicked
on the reset password url
included in the mail
end note

activate Server

Server --> Client : Display reset password form

deactivate Server

activate Client

Client -> Client : Fill form

Client -> Client : Validate form fields

alt Form field is invalid 
    Client -> Client : Display errors messages
end

Client -> Server : Reset password final request

deactivate Client

activate Server

Server -> Server : Verify data sent

alt Form value is invalid 
    Server --> Client : Display errors messages
end

Server -> Database : Update user password

Server ->> SymfonyMailer :  Send success email

Server --> Client : Success message

deactivate Server

@enduml