@startuml
left to right direction

title Blog class diagram

class Comment {
    - id: uuidv4
    - user: ?User
    - author: string
    - content: string
    - createdAt: datetime
    - updatedAt: datetime
    - reports: array[Report]

    addReport() : self
    getReports() : array[Report]
}

class Admin {

}

class User {
    - id: uuidv4
    - username: string
    - email: string
    - password: string
    - role: array
}

class Post {
    - id: uuidv4
    - title: string
    - excerpt: string
    - content: string 
    - slug: string 
    - user: User
    - createdAt: datetime
    - updatedAt: datetime
}

class Report {
    - id: uuidv4
    - createdAt: datetime
}

' Relations
User <|- Admin

Comment "1" --> "0,n" Report : has

Post "1" *.. "0,n" Comment : contains

User "1" <--> "0,n" Post : publish
User "0,1" <--> "0,n" Comment : add

@enduml